# Generated by Django 3.2 on 2024-01-15 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Футболист')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(40, 'Сделай помоложе'), django.core.validators.MinValueValidator(16, 'Сделай постарше')], verbose_name='Возраст футболиста')),
                ('power', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(50, 'Слишком сильный'), django.core.validators.MinValueValidator(10, 'Слишком слабый')], verbose_name='Сила футболиста')),
                ('position', models.CharField(choices=[('ВР', 'Вратарь'), ('ЗЩ', 'Защитник'), ('ПЗ', 'Полузащитник'), ('НП', 'Нападающий')], max_length=2)),
                ('country', models.CharField(choices=[('RU', 'Россия'), ('EN', 'Англия')], max_length=2)),
                ('fatigue', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Усталость футболиста')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название команды')),
                ('city', models.CharField(max_length=255, verbose_name='Команда из города')),
                ('emblem', models.ImageField(blank=True, null=True, upload_to='teams/', verbose_name='Эмблема клуба')),
                ('stadium', models.CharField(max_length=255, verbose_name='Название стадиона команды')),
                ('capacity', models.PositiveIntegerField(default=5000, verbose_name='Вместимость стадиона')),
            ],
        ),
    ]
