# Generated by Django 3.2 on 2023-12-20 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='player10_guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest10', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player10_home',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home10', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player11_guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest11', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player11_home',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home11', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player1_guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest1', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player1_home',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home1', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest2', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_home',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home2', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player3_guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest3', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player3_home',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home3', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player4_guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest4', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player4_home',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home4', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player5_guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest5', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player5_home',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home5', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player6_guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest6', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player6_home',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home6', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player7_guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest7', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player7_home',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home7', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player8_guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest8', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player8_home',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home8', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player9_guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest9', to='teams.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player9_home',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home9', to='teams.player'),
        ),
    ]
